### PR TITLE
Creation of the view for the trip creation feature

### PR DESCRIPTION
**Pull request by JuanSe2003**
I implement the view and the viewModel for the view related to the creation of a trip, with its respective fields and buttons.

### CODE REVIEW

**Comment by CristianCaro915** [comment]
wtf is this mate

**Comment by CristianCaro915** [comment]
my king

**Review by CristianCaro915 — APPROVED** [review]
I understand everything, remember to connect the view with our dataModels and database. This can be done for future issues. Good work my king

**Comment by JuanSe2003** [comment]
I understand your concerns, Cristian, and in a future release, I will implement what you are suggesting.

**Comment by Pabluchenkoo** [comment]
Looks like a lot of work is missing for now, before considering a merge

**Pull request closed without merging**
