### PR TITLE
added connectivity app manager and validations on each button of profile view

### PR DESCRIPTION
**Pull request by Pabluchenkoo**
Take a look to the issue teammates.
Long story short I've implemented a manager for connectivity. So its up on the background. You can use it on your respective view like so:
`@ObservedObject private var connectivityManager = ConnectivityManager.shared`

As it is an observed object it stores the state and then you can make validations on buttons or whatever you need like so:

```
if connectivityManager.isConnected {
                        showConfirmationDialog = true
                    } else {
                        alertMessage = "No internet connection available. Please connect to the internet to continue."
                        showAlert = true
                    }
```

Also in this commit whenever the user losses connection a red banner is displayed on the top of the screen.

### CODE REVIEW

**Comment by Pabluchenkoo** [comment]
@CristianCaro915 @JuanSe2003  let me know what you think about it mates

**Review by JuanSe2003 — APPROVED** [review]
It looks good , and the changes are great

**Comment by CristianCaro915** [comment]
I had a network manager too but the way you managed alerts is better. I had to create alerts in each view with the same generic message. Your way is more efficient my partner

**Review by CristianCaro915 — APPROVED** [review]
I checked everything and no errors were displayed. I will integrate those changes to my current branch

**Comment by Pabluchenkoo** [comment]
great boys

**Pull request merged**
