### PR TITLE
FaceIDworkingFiFo

### PR DESCRIPTION
**Pull request by Pabluchenkoo**

### CODE REVIEW

**Comment by Pabluchenkoo** [comment]
You need to authenticate once at least in order to use the Face ID functionality

**Comment by CristianCaro915** [comment]
i cannot believe it, i wanna test it out myself

**Review by CristianCaro915 — APPROVED** [review]
it seems nice, thanks for your work

**Review by Pabluchenkoo — COMMENTED** [review]
I've tested and it works 10/10

**Pull request merged**
