### PR TITLE
Solve syntax problem

### PR DESCRIPTION
**Pull request by CristianCaro915**
FIX a small mistake when merging, I deleted two symbols in firebase manager. This semi column "}"

### CODE REVIEW

**Review by JuanSe2003 — APPROVED** [review]
Perfect

**Comment by CristianCaro915** [comment]
When merging I deleted two semi columns causing small syntax problems. Now is fixed and tested correctly

**Comment by CristianCaro915** [comment]
I added a filter for ridepickerview in order to display the active trips base on the location selected. Works nice with a filter button on the top right corner

**Review by Pabluchenkoo — APPROVED** [review]
Looks good, merge it when u r ready @CristianCaro915

**Pull request merged**
